version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/app_db
    depends_on:
      - db
      - ml_service  # Opcional para integração com IA

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ml_service:  # Serviço opcional para IA/ML
    image: ml-model-service:latest
    ports:
      - "5001:5000"
    environment:
      - MODEL_NAME=my_ai_model

volumes:
  postgres_data: